---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

clone:
  git:
    recursive: true
    depth: 50
    submodule_update_remote: true
    submodule_override:
      sysbox-ipc: https://github.com/nestybox/sysbox-ipc.git
      sysbox-mgr: https://github.com/nestybox/sysbox-mgr.git
      sysbox-fs: https://github.com/nestybox/sysbox-fs.git
      sysbox-runc: https://github.com/nestybox/sysbox-runc.git
      shiftfs: https://github.com/nestybox/shiftfs.git
      bazil: https://github.com/nestybox/fuse.git

steps:
- name: test
  image: golang:1.12.9
  commands:
  - cd sysbox-fs
  - go test -v ./...

#- name: build
#  image: golang:1.12.9
#  commands:
#  - make sysboxd
#  environment:
#    GOARCH: amd64
#    GOOS: linux

