#!/bin/bash
#
# Copyright: (C) 2019 Nestybox Inc.  All rights reserved.
#
# Description: Script converts a user-defined changelog file into a
# debian-friendly counterpart.
#
# Required input:
#
# User-defined changelog file must necesarily utilize the following layout:
#
# $ cat CHANGELOG.md
# ...
# ## [0.0.2] - unreleased
# ### Added
#  * Generate external documentation: README, user-guide, design-guide, etc.
#  * Extend Sysvisor support to Ubuntu-Bionic.
#
# ## [0.0.1] - 2019-06-23
# ### Added
#  * Initial public release.
#
# Expected output:
#
# $ cat image/deb/common/changelog
# ...
# sysvisor (0.0.2) unstable; urgency=low
#
#  * Generate external documentation: README, user-guide, design-guide, etc.
#  * Extend Sysvisor support to Ubuntu-Bionic.
#
#  -- Rodny Molina <rmolina@nestybox.com> Tue, 20 Aug 2019 16:21:10 -0700
#
# sysvisor (0.0.1) unstable; urgency=low
#
#  * Initial public release.
#
#  -- Rodny Molina <rmolina@nestybox.com> Tue, 23 Jul 2019 17:37:44 -0400
#

# Input file to be created/edited by whoever creates a new Sysvisor release.
user_changelog="sysvisor/CHANGELOG.md"

# Output file to be generated by this script, and to be included in Sysvisor's
# debian-package installer.
debian_changelog="debian/changelog"

# Redirect all generated output.
exec > ${debian_changelog}


print_tag_header() {

    local tag=$1
    local unreleased=$2

    if [[ $unreleased = true ]]; then
        echo -e "sysvisor ($tag-0~${DISTRO}-${SUITE}) ${SUITE} UNRELEASED; urgency=low\n"
    else
        echo -e "sysvisor ($tag-0~${DISTRO}-${SUITE}) ${SUITE} unstable; urgency=low\n"
    fi
}

print_tag_trailer() {

    local tag=$1
    local unreleased=$2

    local tag_author=""
    local tag_email=""
    local tag_date=""


    if [[ "$unreleased" = true ]]; then
        tag_author="Nestybox builder_bot"
        tag_email="builder-bot@nestybox.com"
        tag_date=$(date --rfc-2822)
    else
        # Temporarily commenting these lines out to avoid exposing personal emails.
        #local tag_author=$(git -C sysvisor log -1 --format=%aN v$1)
        #local tag_email=$(git -C sysvisor log -1 --format=%ae v$1)
        tag_author="Nestybox builder_bot"
        tag_email="builder-bot@nestybox.com"
        tag_date=$(git -C sysvisor log -1 --format=%aD v$tag)
    fi
    
    echo -e "\n -- ${tag_author} <${tag_email}>  ${tag_date}\n"    
}

main () {
    local currTag=""
    local prevTag=""
    local unreleased=""

    # Make sure a user-defined changelog is alredy available.
    if [[ ! -f ${user_changelog} ]]; then
        echo "Sysvisor CHANGELOG.md file not found. Exiting..."
        exit 1
    fi

    while IFS= read -r line; do
        if echo ${line} | egrep -q "^## "; then

            currTag=$(echo ${line} | cut -d"[" -f2 | cut -d"]" -f1)
            
            if echo ${line} | egrep -q "unreleased"; then
                unreleased=true
            else
                unreleased=false
            fi

            if [[ ${currTag} != ${prevTag} ]] && [[ ${prevTag} != "" ]]; then
                print_tag_trailer ${prevTag} ${unreleased}
            fi

            print_tag_header ${currTag} ${unreleased}

            prevTag=${currTag}
    
        elif echo "${line}" | egrep -q "^ * "; then
            echo -e "${line}"
        fi

    done < ${user_changelog}

    print_tag_trailer ${currTag} ${unreleased}
}

main
