#!/bin/bash -e

#
# Launch Sysbox (requires root privileges)
#
# Note: normally Sysbox is installed via a distro-specific package
# which sets up the Sysbox systemd units. This script is meant as a
# quick alternative to the installer to help launch Sysbox manually
# (e.g., for testing).
#

# Retry a command $1 times until it succeeds. Wait $2 seconds between retries.
# (copied from runc/tests/integration/helpers.bash)
function retry() {
  local attempts=$1
  shift
  local delay=$1
  shift
  local i

  for ((i = 0; i < attempts; i++)); do
    $@
    if [ "$?" -eq 0 ]; then
	return 0
    fi
    sleep $delay
  done

  echo "Command \"$@\" failed $attempts times. Output: $?"
  false
}

# kill any running sysbox processes
sysmgr_pids=$(pidof sysbox-mgr)
sysfs_pids=$(pidof sysbox-fs)

for pid in $sysmgr_pids; do
   kill $pid
done

for pid in $sysfs_pids; do
   kill $pid
done

# Increase default inotify resources to meet sys container's demands.
sysctl -w fs.inotify.max_queued_events=1048576
sysctl -w fs.inotify.max_user_watches=1048576
sysctl -w fs.inotify.max_user_instances=1048576

# Increase default keyring resources to meet sys container demands.
# For a k8s cluster:
# keys = 35 + (workers * 23) + (2 * pods)
# maxbytes = 20 bytes * maxkeys
sysctl -w kernel.keys.maxkeys=20000
sysctl -w kernel.keys.maxbytes=$((20*20000))

#
# Start Sysbox components
#
mkdir -p /var/lib/sysboxfs
sysbox-mgr --log /dev/stdout > /var/log/sysbox-mgr.log 2>&1 &

RES=$(retry 10 1 grep -q Ready /var/log/sysbox-mgr.log)
if [ $? -ne 0 ]; then
  printf "\nsysbox-mgr failed to start. Here is the log file:\n"
  cat /var/log/sysbox-mgr.log
  exit 1
fi


sysbox-fs --log /dev/stdout > /var/log/sysbox-fs.log 2>&1 &

RES=$(retry 10 1 grep -q Initiating /var/log/sysbox-fs.log)
if [ $? -ne 0 ]; then
  printf "\nsysbox-fs failed to start. Here is the log file:\n"
  cat /var/log/sysbox-fs.log
  exit 1
fi
