#!/bin/bash -e

#
# Sysbox build container initialization script
#

thisHost=$(hostname)

# Build cookie (to build from scratch when necessary only)
if [[ ! -f .buildinfo ]]; then
  touch .buildinfo
  chown rootless:rootless .buildinfo
fi

lastBuildHost=$(cat .buildinfo)
if [[ "$lastBuildHost" != "$thisHost" ]]; then
  make clean
fi

TARGET=$1

# Build sysbox
make $TARGET --no-print-directory
