#!/bin/bash -e

#
# Sysbox-in-Docker (sind) test container initialization script
#

# Dockerd default configuration dir/file.
dockerCfgDir="/etc/docker"
dockerCfgFile="${dockerCfgDir}/daemon.json"

# Default mtu value associated to test-container's egress-interface.
default_mtu=1500

# Temp file for jq write operations.
tmpfile=$(mktemp /tmp/init-scr.XXXXXX)
trap 'rm -f "${tmpfile}"' EXIT


function retry() {
  local attempts=$1
  shift
  local delay=$1
  shift
  local i

  set +e
  for ((i = 0; i < attempts; i++)); do
    $@
    if [ "$?" -eq 0 ]; then
      set -e
      return 0
    fi
    sleep $delay
  done

  set -e
  echo "Command \"$@\" failed $attempts times. Output: $?"
  false
}

#
# Obtain the MTU value to be configured for the docker interface within the test
# container. This value shall be the lowest among these ...
#
#  * The 'physical' default-gateway interface at host level (L0).
#  * The 'logical' default-gateway interface connecting the test-container (L1) with the host.
#  * The 'default' mtu value (1500 bytes) supported by most NICs.
#
function docker_iface_mtu() {

    local egress_iface
    local l0_egress_mtu
    local l1_egress_mtu

    # Identify default egress iface.
    local egress_iface=$(ip route show | awk '/default via/ {print $5}')
    if [ -z "${egress_iface}" ]; then
	return
    fi

    # Obtain mtu value associated to the test-container's egress interface.
    egress_mtu=$(ip link show ${egress_iface} | awk '/mtu / {print $5}')
    if [ ! -z "${egress_mtu}" ] &&
       [ "${egress_mtu}" -lt "${default_mtu}" ]; then
	l1_egress_mtu=${egress_mtu}
    else
	l1_egress_mtu=${default_mtu}
    fi

    # Pull L0 egress-mtu value passed from Sysbox's makefile.
    l0_egress_mtu=${PHY_EGRESS_IFACE_MTU}

    if [ "${l0_egress_mtu}" -lt "${l1_egress_mtu}" ]; then
	echo ${l0_egress_mtu}
    else
	echo ${l1_egress_mtu}
    fi
}


#
# Execution starts here ...
#

# Configure dockerd
mkdir -p "${dockerCfgDir}"
cat <<EOF > "${dockerCfgFile}"
{
    "bip": "172.24.0.1/16",
    "default-address-pools": [
        {
            "base": "172.31.0.0/16",
            "size": 24
        }
    ]
}
EOF

# Adjust docker's interface mtu configuration. This is required to avoid forwarding issues
# in containers seating behind an egress-interface with lower-than-default mtu.
egress_mtu=$(docker_iface_mtu)
if [ ! -z "${egress_mtu}" ] && [ "${egress_mtu}" -ne "${default_mtu}" ]; then
    jq --arg mtu "${egress_mtu}" --indent 4 '. + {"mtu": $mtu|tonumber}' "${dockerCfgFile}" \
       > ${tmpfile} && cp ${tmpfile} "${dockerCfgFile}"
fi

# Start docker
dockerd > /var/log/dockerd.log 2>&1 &
retry 10 0.5 docker ps > /dev/null 2>&1
