#!/bin/bash

#
# Launch sysbox inside the test container
#

set -e

mkdir -p /var/lib/sysboxfs

sysbox-mgr --log /dev/stdout > /var/log/sysbox-mgr.log 2>&1 &

# wait for sysbox-mgr to setup the sysbox work-dir before launching sysbox-fs
sleep 3

# inside the test container we must ignore sysbox-fs handler errors
# when accessing procfs and sysfs, because some procfs and sysfs
# resources are not writeable from within the test container (see
# sysbox issue #538).
sysbox-fs --ignore-handler-errors --log /dev/stdout > /var/log/sysbox-fs.log 2>&1 &

set +e

# wait for sysbox-fs and sysbox-mgr
for ((i = 0; i < 10; i++)); do
  if [ -f /var/log/sysbox-mgr.log ] && [ -f /var/log/sysbox-fs.log ]; then
    mgr_up=$(grep -c "Listening on" /var/log/sysbox-mgr.log)
    fs_up=$(grep -c "Initiating sysbox-fs main-loop" /var/log/sysbox-fs.log)
    if [ "$mgr_up" -eq 1 ] && [ "$fs_up" -eq 1 ]; then
      exit 0
    fi
  fi
  sleep 0.5
done

exit 1
