#!/bin/bash

#
# Launch sysbox inside the test container
#

# Retry a command $1 times until it succeeds. Wait $2 seconds between retries.
# (copied from runc/tests/integration/helpers.bash)
function retry() {
  local attempts=$1
  shift
  local delay=$1
  shift
  local i

  for ((i = 0; i < attempts; i++)); do
    $@
    if [ "$?" -eq 0 ]; then
	return 0
    fi
    sleep $delay
  done

  echo "Command \"$@\" failed $attempts times. Output: $?"
  false
}

mkdir -p /var/lib/sysboxfs
sysbox-mgr --log /dev/stdout > /var/log/sysbox-mgr.log 2>&1 &
retry 5 1 grep -q Ready /var/log/sysbox-mgr.log

# inside the test container we must ignore sysbox-fs handler errors
# when accessing procfs and sysfs, because some procfs and sysfs
# resources are not writeable from within the test container (see
# sysbox issue #538).
sysbox-fs --ignore-handler-errors --log /dev/stdout > /var/log/sysbox-fs.log 2>&1 &
retry 5 1 grep -q Initiating /var/log/sysbox-fs.log

exit 0
