#!/bin/bash -e

#
# Test container initialization script
#
# TODO: Build & install shiftfs (if uid-shift option set)
#

# Build & install sysboxd
thisHost=$(hostname)

# Build cookie (to build from scratch when necessary only)
if [[ ! -f .buildinfo ]]; then
  touch .buildinfo
  chown rootless:rootless .buildinfo
fi

lastBuildHost=$(cat .buildinfo)
if [[ "$lastBuildHost" != "$thisHost" ]]; then
  make clean
fi

make sysboxd --no-print-directory && make install

# Configure dockerd
mkdir -p /etc/docker

if [ -z "$SHIFT_UIDS" ]; then
    cat <<EOF > /etc/docker/daemon.json
{
    "debug": false,
    "userns-remap": "sysboxd",
    "runtimes": {
        "sysbox-runc": {
            "path": "/usr/local/sbin/sysbox-runc"
        }
    }
}
EOF
else
    cat <<EOF > /etc/docker/daemon.json
{
    "debug": false,
    "userns-remap": "",
    "runtimes": {
        "sysbox-runc": {
            "path": "/usr/local/sbin/sysbox-runc",
            "runtimeArgs": [
                "--no-kernel-check"
            ]
        }
    }
}
EOF
fi

# Start sysboxd
sysboxd

# Start docker
dockerd > /var/log/dockerd.log 2>&1 &

# Wait for docker to be up
set +e

for ((i = 0; i < 10; i++)); do
  docker ps > /dev/null 2>&1
  if [ "$?" -eq 0 ]; then
    exit 0
  fi
  sleep 0.5
done

exit 1
