#!/bin/bash

TEST_VOL1=$1
TEST_VOL2=$2
TEST_VOL3=$3

# Check that the host meets sysbox-runc distro requirements (this
# can't be checked from within the test container since its docker
# image may be based on another distro)

DISTRO=$(lsb_release -i | awk '{print $3}')
if [ "$DISTRO" != "Ubuntu" ]; then
  printf "\nError: sysbox uid shifting is only supported on Ubuntu hosts.\n\n"
  exit 1
fi

# See Makefile for description of test volumes
mkdir -p $TEST_VOL1
mkdir -p $TEST_VOL2
mkdir -p $TEST_VOL3

# Build kind-sysbox to be utilized within test container.
make kind-sysbox
