#!/bin/bash -e

#
# Test container initialization script
#
# TODO: Build & install shiftfs (if uid-shift option set)
#

# Build & install sysvisor
thisHost=$(hostname)

# Build cookie (to build from scratch when necessary only)
if [[ ! -f .buildinfo ]]; then
  touch .buildinfo
  chown rootless:rootless .buildinfo
fi

lastBuildHost=$(cat .buildinfo)
if [[ "$lastBuildHost" != "$thisHost" ]]; then
  make clean
fi

make sysvisor --no-print-directory && make install

# Configure dockerd
mkdir -p /etc/docker

if [ -z "$SHIFT_UIDS" ]; then
    cat <<EOF > /etc/docker/daemon.json
{
    "debug": false,
    "userns-remap": "sysvisor",
    "runtimes": {
        "sysvisor-runc": {
            "path": "/usr/local/sbin/sysvisor-runc"
        }
    }
}
EOF
else
    cat <<EOF > /etc/docker/daemon.json
{
    "debug": false,
    "userns-remap": "",
    "runtimes": {
        "sysvisor-runc": {
            "path": "/usr/local/sbin/sysvisor-runc",
            "runtimeArgs": [
                "--no-kernel-check"
            ]
        }
    }
}
EOF
fi

# Start sysvisor
sysvisor

# Start docker
dockerd > /var/log/dockerd.log 2>&1 &
